package project.android.headli9es;

import android.content.Context;
import android.text.TextUtils;
import android.util.Log;

import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.List;

public final class Search {

    private final static String LOG_TAG = Search.class.getName();
    private static String mAPICode;

    private static Context mAppContext;

    // Make class non-instantiable; not a singleton either
    private Search () {
    }

    /**
     *
     * @param context of the app
     * @param requestURL an initial, un-parsed search query
     * @param apiCode used locally as code to determine selected {@link News} API.
     * @return a {@link List} of {@link News} objects.
     */
    protected static List<News> lookupArticles (Context context, String requestURL, String apiCode) {

        mAPICode = apiCode;
        mAppContext = context;

        // Create URL obj
        URL url = createURL(requestURL);

        // Perform HTTP request to the URL and receive a JSON response back
        String JSONResponse = null;

        try {
            JSONResponse = makeHTTPRequest(url);
        } catch (IOException requestException) {
            Log.i(LOG_TAG, "makeHTTPRequest(): " + requestException);
        }

        // Generate a list of newsList from fetched JSON
        return extractJSONData(JSONResponse);
    }

    /**
     * @param stringURL generated by {@link MainActivity}
     * @return a {@link URL} object that could be utilized over the net to send/receive request(s).
     */
    private static URL createURL (String stringURL) {
        URL url = null;
        try {
            url = new URL(stringURL);
        } catch (MalformedURLException mURLE) {
            Log.i(LOG_TAG, mURLE.toString());
        }
        return url;
    }

    /**
     * @param url parsed by method createURL
     * @return JSON response from the request sent to server.
     * @throws IOException if there's a problem with the radio making connection.
     */
    private static String makeHTTPRequest (URL url) throws IOException {
        String JSONResponse = "";

        // If the URL is null, then return early
        if (url == null) {
            return JSONResponse;
        }

        HttpURLConnection urlConn = null;
        InputStream inputStream = null;

        try {
            urlConn = (HttpURLConnection) url.openConnection();
            urlConn.setRequestMethod("GET");

            // Headers to fix NEWS API returning error 403
            if (mAPICode.equals(mAppContext.getString(R.string.news_code))) {
                urlConn.setRequestProperty("User-Agent", "newsapi.org (detective.khalifah.dtcfscd@gmail.com)");
                urlConn.setRequestProperty("Accept", "application/geo+json;version=1");
            }

            urlConn.connect();

            // If the request was successful (response code 200), then read the input stream and
            // parse the response.
            int responseCode = urlConn.getResponseCode();
            Log.i(LOG_TAG, "getResponseCode" + urlConn.getResponseCode());
            if (responseCode == HttpURLConnection.HTTP_OK) {

                inputStream = urlConn.getInputStream();

                JSONResponse = readFromStream(inputStream);
            } else {
                Log.i(LOG_TAG, "from makeHTTPRequest responseCode:: " + urlConn.getResponseCode()
                        + "\nresponseMessage::" + urlConn.getResponseMessage()
                        + "\nErrorStream:: " + urlConn.getErrorStream().read());
                getJSONErrorMessage(readFromStream(urlConn.getInputStream()));
            }
        } catch (IOException e) {
            Log.i(LOG_TAG, "urlConn: " + e);
        } finally {
            if (urlConn != null)
                urlConn.disconnect();
            if (inputStream != null)
                inputStream.close();
        }
        return JSONResponse;
    }

    /**
     * @param inStream received from net server.
     * @return a {@link String} value of the stream.
     * @throws IOException while processing {@link InputStream} if there's something amiss!
     */
    private static String readFromStream (InputStream inStream) throws IOException {
        StringBuilder myList = new StringBuilder();
        if (inStream != null) {
            InputStreamReader inStreamDecode = new InputStreamReader(inStream);
            BufferedReader reader = new BufferedReader(inStreamDecode);

            String line = reader.readLine();
            while (line != null) {
                myList.append(line);
                line = reader.readLine();
            }
        }
        return myList.toString();
    }

    private static List<News> extractJSONData (String newsJSONResponse) {

        // If the JSON String is empty or null, then return early.
        if (TextUtils.isEmpty(newsJSONResponse))
            return null;

        // Create an empty ArrayList that we can start adding newsList to
        List<News> news = new ArrayList<>();

        // Try to parse the SAMPLE_JSON_RESPONSE. If there's a problem with the way the JSON
        // is formatted, a JSONException exception object will be thrown.
        // Catch the exception so the app doesn't crash, and print the error message to the logs.
        // Otherwise, build up a list of News objects with the corresponding data.
        try {

            // Create a JSON object from the SAMPLE_JSON_RESPONSE string
            JSONObject rootJSONObj = new JSONObject(newsJSONResponse);

            if (mAPICode.equals(mAppContext.getString(R.string.ny_times_code))) {
                /** From root JSON OBJ:: {@link articlesNumber}, {@link articlesArray},
                 *  {@link copyrright}, {@link section}, {@link status}, {@link last_updated} */
                // Number of articles
                int articlesNumber = rootJSONObj.getInt("num_results");

                // Extract the JSONArray associated with the key called "results"
                // which represents a list newsList.
                JSONArray results = rootJSONObj.getJSONArray("results");

                // For each article in the results, create a {@link news} object
                for (int i = 0; i < results.length(); i++) {
                    JSONObject currentArticle = results.getJSONObject(i);

                    // Extract content
                    String description = currentArticle.optString("abstract");

                    /* Extract publish_date*/
                    String publish_date = currentArticle.optString("published_date");

                    // Extract news sourceName
                    String sourceName = currentArticle.optString("byline");

                    // Extract title
                    String title = currentArticle.optString("title");

                    // Extract news link - a uri for the current article, which can be used to
                    // uniquely open article info online
                    String web_page = currentArticle.optString("url");

                    news.add(new News(title, publish_date, web_page, sourceName,
                            description, articlesNumber));
                }
            } else if (mAPICode.equals(mAppContext.getString(R.string.news_code))) {
                int totalResults = rootJSONObj.getInt("totalResults");

                JSONArray articles1 = rootJSONObj.getJSONArray("articles");
                for (int i = 0; i < articles1.length(); i++) {
                    JSONObject currentResult = articles1.getJSONObject(i);

                    String source = currentResult.getJSONObject("source").getString("name");
                    String title = currentResult.getString("title");
                    String description = currentResult.getString("description");
                    String date = currentResult.getString("publishedAt");
                    String page = currentResult.getString("url");

                    // Handle cases where 'description' is null by replacing with 'content'
                    if (description.equalsIgnoreCase("null")) {
                        description = currentResult.getString("content");
                        if (description.equalsIgnoreCase("null")) {
                            description = (String) "Click to learn more at " + source;
                        }
                    }
                    news.add(new News(title, date, page, source,
                            description, totalResults));
                }
            } else { // Guardian API
                JSONObject response = rootJSONObj.getJSONObject("response");

                int totalArticles = response.getInt("total");
                int pageSize = response.getInt("pageSize");

                JSONArray articles = response.getJSONArray("results");

                for (int i = 0; i < articles.length(); i++) {
                    JSONObject currentArticle = articles.getJSONObject(i);

                    String category = currentArticle.getString("sectionName");
                    String date = (String) currentArticle.get("webPublicationDate");

                    String title = currentArticle.getString("webTitle");
                    String page = currentArticle.getString("webUrl");

                    news.add(new News(title, date, page, category,
                            totalArticles, pageSize));

                }
            }

        } catch (JSONException e) {
            // If an error is thrown when executing any of the above statements in the switch
            // statement of the "try" block,
            // catch the exception here, so the app doesn't crash. Print a log message
            // with the message from the exception.
            Log.i(LOG_TAG, "Problem parsing the JSON results_page", e);
            if (mAPICode.equals("NEWS_API")) {
                JSONObject root = null;
                try {
                    root = new JSONObject(newsJSONResponse);
                    Log.i(LOG_TAG, "status: " + root.getString("status")
                            + "\ncode: " + root.getString("code")
                            + "\nmessage: " + root.getString("message")
                    );
                } catch (JSONException ex) {
                    Log.i(LOG_TAG, ex.toString());
                }
            }
        }

        // Return the list (polymorphed ArrayList) of newsList
        return news;
    }

    private static void getJSONErrorMessage (String JSON) {
        if (mAPICode.equals("NEWS_API")) {
            JSONObject root;
            try {
                root = new JSONObject(JSON);
                Log.i(LOG_TAG, "status: " + root.getString("status")
                        + "\ncode: " + root.getString("code")
                        + "\nmessage: " + root.getString("message")
                );
            } catch (JSONException ex) {
                Log.i(LOG_TAG, ex.toString());
            }
        }
    }
}